//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.06 at 10:36:33 AM EEST 
//


package ua.epam.spring.hometask.soap.message;

import ua.epam.spring.hometask.soap.xmladapter.AdaptedMap;
import ua.epam.spring.hometask.soap.xmladapter.Entry;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DeleteUserRequest_QNAME = new QName("", "deleteUserRequest");
    private final static QName _GetUserResponse_QNAME = new QName("", "getUserResponse");
    private final static QName _AddUserRequest_QNAME = new QName("", "addUserRequest");
    private final static QName _GetEventResponse_QNAME = new QName("", "getEventResponse");
    private final static QName _AddEventRequest_QNAME = new QName("", "addEventRequest");
    private final static QName _AddEventResponse_QNAME = new QName("", "addEventResponse");
    private final static QName _DeleteEventRequest_QNAME = new QName("", "deleteEventRequest");
    private final static QName _GetUserRequest_QNAME = new QName("", "getUserRequest");
    private final static QName _AddUserResponse_QNAME = new QName("", "addUserResponse");
    private final static QName _DeleteUserResponse_QNAME = new QName("", "deleteUserResponse");
    private final static QName _DeleteEventResponse_QNAME = new QName("", "deleteEventResponse");
    private final static QName _GetEventRequest_QNAME = new QName("", "getEventRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteUserRequest }
     * 
     */
    public DeleteUserRequest createDeleteUserRequest() {
        return new DeleteUserRequest();
    }

    /**
     * Create an instance of {@link GetUserResponse }
     * 
     */
    public GetUserResponse createGetUserResponse() {
        return new GetUserResponse();
    }

    /**
     * Create an instance of {@link AddUserRequest }
     * 
     */
    public AddUserRequest createAddUserRequest() {
        return new AddUserRequest();
    }

    /**
     * Create an instance of {@link GetEventResponse }
     * 
     */
    public GetEventResponse createGetEventResponse() {
        return new GetEventResponse();
    }

    /**
     * Create an instance of {@link AddEventRequest }
     * 
     */
    public AddEventRequest createAddEventRequest() {
        return new AddEventRequest();
    }

    /**
     * Create an instance of {@link AddEventResponse }
     * 
     */
    public AddEventResponse createAddEventResponse() {
        return new AddEventResponse();
    }

    /**
     * Create an instance of {@link DeleteEventRequest }
     * 
     */
    public DeleteEventRequest createDeleteEventRequest() {
        return new DeleteEventRequest();
    }

    /**
     * Create an instance of {@link GetUserRequest }
     * 
     */
    public GetUserRequest createGetUserRequest() {
        return new GetUserRequest();
    }

    /**
     * Create an instance of {@link AddUserResponse }
     * 
     */
    public AddUserResponse createAddUserResponse() {
        return new AddUserResponse();
    }

    /**
     * Create an instance of {@link DeleteUserResponse }
     * 
     */
    public DeleteUserResponse createDeleteUserResponse() {
        return new DeleteUserResponse();
    }

    /**
     * Create an instance of {@link DeleteEventResponse }
     * 
     */
    public DeleteEventResponse createDeleteEventResponse() {
        return new DeleteEventResponse();
    }

    /**
     * Create an instance of {@link GetEventRequest }
     * 
     */
    public GetEventRequest createGetEventRequest() {
        return new GetEventRequest();
    }

    /**
     * Create an instance of {@link AdaptedMap }
     *
     */
    public AdaptedMap createAdaptedMap() {
        return new AdaptedMap();
    }

    /**
     * Create an instance of {@link Entry }
     *
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteUserRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deleteUserRequest")
    public JAXBElement<DeleteUserRequest> createDeleteUserRequest(DeleteUserRequest value) {
        return new JAXBElement<DeleteUserRequest>(_DeleteUserRequest_QNAME, DeleteUserRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "getUserResponse")
    public JAXBElement<GetUserResponse> createGetUserResponse(GetUserResponse value) {
        return new JAXBElement<GetUserResponse>(_GetUserResponse_QNAME, GetUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddUserRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addUserRequest")
    public JAXBElement<AddUserRequest> createAddUserRequest(AddUserRequest value) {
        return new JAXBElement<AddUserRequest>(_AddUserRequest_QNAME, AddUserRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEventResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "getEventResponse")
    public JAXBElement<GetEventResponse> createGetEventResponse(GetEventResponse value) {
        return new JAXBElement<GetEventResponse>(_GetEventResponse_QNAME, GetEventResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddEventRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addEventRequest")
    public JAXBElement<AddEventRequest> createAddEventRequest(AddEventRequest value) {
        return new JAXBElement<AddEventRequest>(_AddEventRequest_QNAME, AddEventRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddEventResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addEventResponse")
    public JAXBElement<AddEventResponse> createAddEventResponse(AddEventResponse value) {
        return new JAXBElement<AddEventResponse>(_AddEventResponse_QNAME, AddEventResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteEventRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deleteEventRequest")
    public JAXBElement<DeleteEventRequest> createDeleteEventRequest(DeleteEventRequest value) {
        return new JAXBElement<DeleteEventRequest>(_DeleteEventRequest_QNAME, DeleteEventRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "getUserRequest")
    public JAXBElement<GetUserRequest> createGetUserRequest(GetUserRequest value) {
        return new JAXBElement<GetUserRequest>(_GetUserRequest_QNAME, GetUserRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "addUserResponse")
    public JAXBElement<AddUserResponse> createAddUserResponse(AddUserResponse value) {
        return new JAXBElement<AddUserResponse>(_AddUserResponse_QNAME, AddUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deleteUserResponse")
    public JAXBElement<DeleteUserResponse> createDeleteUserResponse(DeleteUserResponse value) {
        return new JAXBElement<DeleteUserResponse>(_DeleteUserResponse_QNAME, DeleteUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteEventResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "deleteEventResponse")
    public JAXBElement<DeleteEventResponse> createDeleteEventResponse(DeleteEventResponse value) {
        return new JAXBElement<DeleteEventResponse>(_DeleteEventResponse_QNAME, DeleteEventResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEventRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "getEventRequest")
    public JAXBElement<GetEventRequest> createGetEventRequest(GetEventRequest value) {
        return new JAXBElement<GetEventRequest>(_GetEventRequest_QNAME, GetEventRequest.class, null, value);
    }

}
